# Generated by Django 4.1.6 on 2023-02-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ShareBox", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="product"),
        ),
    ]
